version: "3.9"

services:
  db:
    container_name: database
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - djangoapp
  web:
    container_name: backend
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangoapp
    command: python manage.py runserver 0.0.0.0:8000
  
networks:
  djangoapp:
      driver: bridge