# Generated by Django 4.1 on 2022-09-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('tp', 'Tempo Kondela'), ('ps', 'Posed')], max_length=20)),
                ('orderType', models.CharField(choices=[('cs', 'Customer'), ('st', 'Storage'), ('cp', 'Complaint')], default='cs', max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('received', models.DateField()),
                ('informedProducer', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orderentry',
            name='productID',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='dispatched',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='status',
            field=models.CharField(choices=[('st', 'Sent'), ('ip', 'In production'), ('cc', 'Canceled'), ('rt', 'Returned')], default='ip', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='orderEntryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.orderentry'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.SmallIntegerField()),
                ('group', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], default='1', max_length=10)),
                ('orderEntryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listing.orderentry')),
            ],
        ),
        migrations.AddField(
            model_name='orderentry',
            name='orderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.order'),
            preserve_default=False,
        ),
    ]
