# Generated by Django 4.1 on 2022-09-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_order_remove_orderentry_productid_orderentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabric',
            name='orderEntryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.orderentry'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='orderEntryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.orderentry'),
        ),
    ]
