# Generated by Django 4.1 on 2022-09-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_product_family_alter_fabric_orderentryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='orderEntryId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orderEntryId',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='fabricId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.fabric'),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='productId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.product'),
        ),
    ]
