# Generated by Django 4.1 on 2022-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_remove_fabric_orderentryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='informedProducer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
