# Generated by Django 4.1 on 2022-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_order_informedproducer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pd', 'Pending'), ('ct', 'Complited')], default='pd', max_length=50),
        ),
    ]
