# Generated by Django 4.1 on 2022-09-07 14:29

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('listing', '0008_myusermanager_alter_order_number_alter_product_ean'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUserManager',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
